create table user_account
(
    id         int8    not null GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name  varchar(16) unique,
    password   varchar(255),
    first_name varchar(16),
    last_name  varchar(16),
    role       varchar(16),
    active     boolean not null,
    created_at timestamp DEFAULT current_timestamp
);


